name: 03_challenge

on: push

env:
  ARTIFACT_NAME: ArtifactName

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: $ARTIFACT_NAME
          path: path/to/artifact/world.txt
